type User {
  id: Int!
  username: String!
  email: String!
  created_at: String!
  updated_at: String
}

type Token {
  token: String!
  expiresIn: String!
}

type UserConnected {
  id: Int!
  username: String!
  email: String!
  token: Token!
  created_at: String!
  updated_at: String
}
